// GENERATED by server/scripts/sync-shared.js from shared/ -- do not edit directly.
const SPORT_KEYS = ['SOCCER', 'BASKETBALL', 'TENNIS'];

const SPORT_MAPPING = {
  SOCCER: 'כדורגל',
  BASKETBALL: 'כדורסל',
  TENNIS: 'טניס',
};

const SPORT_EMOJI = {
  SOCCER: '⚽',
  BASKETBALL: '🏀',
  TENNIS: '🎾',
};

const POSITION_OPTIONS = {
  SOCCER: ['שוער', 'בלם', 'מגן', 'קשר', 'חלוץ'],
  BASKETBALL: ['פוינט גארד', 'שוטינג גארד', 'סמול פורוורד', 'פאואר פורוורד', 'סנטר'],
  TENNIS: ['שחקן בסיס', 'שחקן רשת'],
};

const HEBREW_SPORT_MAP = {
  'כדורגל': 'SOCCER',
  'רגל': 'SOCCER',
  'כדורסל': 'BASKETBALL',
  'סל': 'BASKETBALL',
  'טניס': 'TENNIS',
};

function resolveSportFilters(q) {
  const query = String(q || '').trim();
  if (!query) return [];
  const lowerQ = query.toLowerCase();
  const matches = new Set(
    SPORT_KEYS.filter((s) => s.toLowerCase().includes(lowerQ))
  );
  for (const [hebrew, enumValue] of Object.entries(HEBREW_SPORT_MAP)) {
    if (hebrew.includes(query) || query.includes(hebrew)) {
      matches.add(enumValue);
    }
  }
  return [...matches];
}

module.exports = {
  SPORT_KEYS,
  SPORT_MAPPING,
  SPORT_EMOJI,
  POSITION_OPTIONS,
  HEBREW_SPORT_MAP,
  resolveSportFilters,
};
