export type Game = {
    id: string;
    fieldId: string;
    fieldName: string;
    fieldLocation: string;
    city?: string | null;
    start?: string;
    date: string;
    time: string;
    duration?: number;
    maxPlayers: number;
    currentPlayers: number;
    participants?: Array<{ id: string; name?: string | null }>;
    sport?: string;
    seriesId?: string | null;
    registrationOpensAt?: string | null;
    title?: string | null;
    teamSize?: number | null;
    price?: number | null;
    organizerId?: string;
    fieldLat?: number | null;
    fieldLng?: number | null;
    customLat?: number | null;
    customLng?: number | null;
    isFriendsOnly?: boolean;
    joinPolicy?: 'INSTANT' | 'REQUIRES_APPROVAL';
    pendingRequestCount?: number;
    viewerParticipationStatus?: 'PENDING' | 'CONFIRMED' | 'WAITLISTED' | 'REJECTED' | null;
    field?: {
        lat?: number | null;
        lng?: number | null;
        name?: string;
    };
};
