// Vendors the shared/ modules server actually requires into server/shared/, since Render's
// Docker build context is scoped to server/ and can't COPY anything from the sibling shared/
// directory at the repo root. Run this after editing shared/{timezone,sports,upload}.js and
// commit the result -- server/shared/ is generated, not hand-edited.
const fs = require('fs');
const path = require('path');

const ROOT_SHARED = path.join(__dirname, '..', '..', 'shared');
const VENDORED = path.join(__dirname, '..', 'shared');
const FILES = ['timezone.js', 'sports.js', 'upload.js'];

const HEADER = '// GENERATED by server/scripts/sync-shared.js from shared/ -- do not edit directly.\n';

fs.mkdirSync(VENDORED, { recursive: true });

for (const file of FILES) {
  const src = fs.readFileSync(path.join(ROOT_SHARED, file), 'utf8');
  fs.writeFileSync(path.join(VENDORED, file), HEADER + src);
  console.log(`[sync-shared] wrote server/shared/${file}`);
}
